#!/usr/bin/env bash
# Tests for check_artifact_freshness() in scripts/uat-helpers.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$REPO_ROOT"

# Ensure a workspace-local temp dir exists (avoid /tmp)
mkdir -p .tmp/tests-shell
test_dir=".tmp/tests-shell/freshness-test-$$"
mkdir -p "$test_dir"

cleanup() {
  rm -rf "$test_dir" || true
}
trap cleanup EXIT

# Source helper
# shellcheck source=scripts/uat-helpers.sh
source scripts/uat-helpers.sh

fail=0
current_short="$(git rev-parse --short HEAD 2>/dev/null || echo "")"

# ──────────────────────────────────────────────────────────────────────────────
# Test 1: Artifact with no "Generated by" header → warn + return 0
# ──────────────────────────────────────────────────────────────────────────────
echo "# artifact without header" > "$test_dir/no-header.md"
if check_artifact_freshness "$test_dir/no-header.md" 2>/dev/null; then
  echo "OK: artifact without header allowed (warning only)"
else
  echo "ERROR: artifact without header should be allowed (warn only)"
  fail=1
fi

# ──────────────────────────────────────────────────────────────────────────────
# Test 2: Artifact with current HEAD hash → return 0 (up-to-date)
# ──────────────────────────────────────────────────────────────────────────────
if [[ -n "$current_short" ]]; then
  echo "Generated by tfplan2md 1.0.0 (${current_short}) on 2026-01-01 00:00:00 UTC" > "$test_dir/current.md"
  echo "# content" >> "$test_dir/current.md"
  if check_artifact_freshness "$test_dir/current.md" 2>/dev/null; then
    echo "OK: artifact with current HEAD hash accepted"
  else
    echo "ERROR: artifact with current HEAD hash should be accepted"
    fail=1
  fi
fi

# ──────────────────────────────────────────────────────────────────────────────
# Test 3: Artifact with unknown commit hash → warn + return 0
# ──────────────────────────────────────────────────────────────────────────────
echo "Generated by tfplan2md 1.0.0 (deadbeef) on 2026-01-01 00:00:00 UTC" > "$test_dir/unknown-hash.md"
echo "# content" >> "$test_dir/unknown-hash.md"
if check_artifact_freshness "$test_dir/unknown-hash.md" 2>/dev/null; then
  echo "OK: artifact with unknown commit hash allowed (warn only)"
else
  echo "ERROR: artifact with unknown commit hash should be allowed (warn only)"
  fail=1
fi

# ──────────────────────────────────────────────────────────────────────────────
# Test 4: Missing artifact file → return 1
# ──────────────────────────────────────────────────────────────────────────────
if check_artifact_freshness "$test_dir/does-not-exist.md" 2>/dev/null; then
  echo "ERROR: missing artifact should return non-zero"
  fail=1
else
  echo "OK: missing artifact returns non-zero"
fi

# ──────────────────────────────────────────────────────────────────────────────
# Test 5: Actual artifact files in artifacts/ have the current or older commit
#         (They should pass freshness check since we're on a workflow-only branch)
# ──────────────────────────────────────────────────────────────────────────────
if [[ -f "artifacts/comprehensive-demo.md" ]]; then
  if check_artifact_freshness "artifacts/comprehensive-demo.md" 2>/dev/null; then
    echo "OK: artifacts/comprehensive-demo.md freshness check passed"
  else
    echo "WARN: artifacts/comprehensive-demo.md is stale (expected on code-change branches)"
  fi
fi

# ──────────────────────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────────────────────
if [[ $fail -ne 0 ]]; then
  echo "One or more tests failed." >&2
  exit 1
fi

echo "All freshness tests passed."
